// IconId.cs
namespace ProfileEditor
{
    public enum IconId
    {
        ICON_PROFILE_PREV = 0,
        ICON_PROFILE_NEXT = 1,
        ICON_UNDO = 2,
        ICON_BRUSH = 3,
        ICON_PENCIL = 4,
        ICON_ERASER = 5,
        ICON_PAINT = 6,
        ICON_SHIFT = 7,
        ICON_CTRL = 8,
        ICON_ALT = 9,
        ICON_MOUSE_RIGHT = 10,
        ICON_MARQUEE = 11,
        ICON_LASSO = 12,
        ICON_SPACE = 13,
        ICON_DELETE = 14,
        ICON_FILL = 15,
        ICON_SELECTION = 16,
        ICON_ZOOM = 17,
        ICON_ROTATE = 18,
        ICON_BRUSH_SIZE = 19,
        ICON_PEN = 20,
        ICON_DIRECT = 21,
        ICON_PEN_ADD = 22,
        ICON_PEN_DEL = 23,
        ICON_ANC = 24,
        ICON_JOIN = 25,
        ICON_NODE = 26,
        ICON_SPOIT = 27,
        ICON_TEXT = 28,
        ICON_SDELETE = 29,
        ICON_SINVERT = 30,
        ICON_GIRL = 31,
        ICON_MOUSE = 32,
        ICON_MOUSE_LEFT = 33,
        ICON_QUICKMASK = 34,
        ICON_REDO = 35,
        ICON_TIMELINE = 36,
        ICON_ZOOM_AREA = 37,
        ICON_SALL = 38,
        ICON_AE = 39,
        ICON_AI = 40,
        ICON_ALPACA = 41,
        ICON_GIMP = 42,
        ICON_INKSCAPE = 43,
        ICON_PS = 44,
        ICON_HAND = 45,
        ICON_U = 46,
        ICON_E = 47,
        ICON_OTHER1 = 48,
        ICON_OTHER2 = 49
    }
}